# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ramadan.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lcdNumberIshaa = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lcdNumberIshaa.setFont(font)
        self.lcdNumberIshaa.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberIshaa.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberIshaa.setLineWidth(2)
        self.lcdNumberIshaa.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberIshaa.setObjectName("lcdNumberIshaa")
        self.horizontalLayout.addWidget(self.lcdNumberIshaa)
        self.checkBoxIshaa = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxIshaa.setText("")
        self.checkBoxIshaa.setObjectName("checkBoxIshaa")
        self.horizontalLayout.addWidget(self.checkBoxIshaa)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lcdNumberImsak = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberImsak.setFont(font)
        self.lcdNumberImsak.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberImsak.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberImsak.setLineWidth(2)
        self.lcdNumberImsak.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberImsak.setObjectName("lcdNumberImsak")
        self.horizontalLayout_2.addWidget(self.lcdNumberImsak)
        self.checkBoxImsak = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxImsak.setText("")
        self.checkBoxImsak.setObjectName("checkBoxImsak")
        self.horizontalLayout_2.addWidget(self.checkBoxImsak)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lcdNumberFajr = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberFajr.setFont(font)
        self.lcdNumberFajr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberFajr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberFajr.setLineWidth(2)
        self.lcdNumberFajr.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberFajr.setObjectName("lcdNumberFajr")
        self.horizontalLayout_3.addWidget(self.lcdNumberFajr)
        self.checkBoxFajr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFajr.setText("")
        self.checkBoxFajr.setObjectName("checkBoxFajr")
        self.horizontalLayout_3.addWidget(self.checkBoxFajr)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.lcdNumberDhuhr = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberDhuhr.setFont(font)
        self.lcdNumberDhuhr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberDhuhr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberDhuhr.setLineWidth(2)
        self.lcdNumberDhuhr.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberDhuhr.setObjectName("lcdNumberDhuhr")
        self.horizontalLayout_4.addWidget(self.lcdNumberDhuhr)
        self.checkBoxDhuhr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxDhuhr.setText("")
        self.checkBoxDhuhr.setObjectName("checkBoxDhuhr")
        self.horizontalLayout_4.addWidget(self.checkBoxDhuhr)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.lcdNumberAsr = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberAsr.setFont(font)
        self.lcdNumberAsr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberAsr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberAsr.setLineWidth(2)
        self.lcdNumberAsr.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberAsr.setObjectName("lcdNumberAsr")
        self.horizontalLayout_5.addWidget(self.lcdNumberAsr)
        self.checkBoxAsr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAsr.setText("")
        self.checkBoxAsr.setObjectName("checkBoxAsr")
        self.horizontalLayout_5.addWidget(self.checkBoxAsr)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.lcdNumberMaghrib = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberMaghrib.setFont(font)
        self.lcdNumberMaghrib.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberMaghrib.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberMaghrib.setLineWidth(2)
        self.lcdNumberMaghrib.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberMaghrib.setObjectName("lcdNumberMaghrib")
        self.horizontalLayout_6.addWidget(self.lcdNumberMaghrib)
        self.checkBoxMaghrib = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxMaghrib.setText("")
        self.checkBoxMaghrib.setObjectName("checkBoxMaghrib")
        self.horizontalLayout_6.addWidget(self.checkBoxMaghrib)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDate.setFont(font)
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.horizontalLayout_7.addWidget(self.labelDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.labelHijri = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelHijri.setFont(font)
        self.labelHijri.setText("")
        self.labelHijri.setObjectName("labelHijri")
        self.horizontalLayout_8.addWidget(self.labelHijri)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.labelTadarus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTadarus.setFont(font)
        self.labelTadarus.setText("")
        self.labelTadarus.setObjectName("labelTadarus")
        self.horizontalLayout_9.addWidget(self.labelTadarus)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.labelCity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCity.setFont(font)
        self.labelCity.setObjectName("labelCity")
        self.horizontalLayout_10.addWidget(self.labelCity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.labelWeather = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelWeather.setFont(font)
        self.labelWeather.setText("")
        self.labelWeather.setObjectName("labelWeather")
        self.horizontalLayout_11.addWidget(self.labelWeather)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.labelTemperature = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTemperature.setFont(font)
        self.labelTemperature.setText("")
        self.labelTemperature.setObjectName("labelTemperature")
        self.horizontalLayout_12.addWidget(self.labelTemperature)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(2, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_13.addWidget(self.timeEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_3)
        spacerItem12 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.lcdNumberClock = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberClock.sizePolicy().hasHeightForWidth())
        self.lcdNumberClock.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumberClock.setFont(font)
        self.lcdNumberClock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberClock.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberClock.setLineWidth(2)
        self.lcdNumberClock.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumberClock.setProperty("intValue", 0)
        self.lcdNumberClock.setObjectName("lcdNumberClock")
        self.horizontalLayout_14.addWidget(self.lcdNumberClock)
        self.horizontalLayout_14.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_16.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Siregar Ramadan Information System</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Ishaa"))
        self.label_6.setText(_translate("MainWindow", "Imsak"))
        self.label.setText(_translate("MainWindow", "Fajr"))
        self.label_2.setText(_translate("MainWindow", "Dhuhr"))
        self.label_3.setText(_translate("MainWindow", "Asr"))
        self.label_4.setText(_translate("MainWindow", "Maghrib"))
        self.label_7.setText(_translate("MainWindow", "Date"))
        self.label_12.setText(_translate("MainWindow", "Hijri"))
        self.label_13.setText(_translate("MainWindow", "Tadarus"))
        self.label_11.setText(_translate("MainWindow", "City"))
        self.labelCity.setText(_translate("MainWindow", "Lund"))
        self.label_10.setText(_translate("MainWindow", "Weather"))
        self.label_14.setText(_translate("MainWindow", "Temperature"))
        self.label_8.setText(_translate("MainWindow", "Alarm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

